
package com.is210q12022.is210.sistema.restaurante;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Cesar Maldonado
 */
public class Meseroejemplo extends javax.swing.JFrame {
    
    public DefaultTableModel model;
    
    public Connection Conectar() {
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://is210-sistema-restaurante.database.windows.net:1433;databaseName=dbo;database=Restaurante;user=MasterChief@is210-sistema-restaurante;password={};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;","devLogin","is210-2022-student!");
        } catch (SQLException e) {
            System.err.print(e.toString());
            JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado.\nFavor comunicarse con el administrador.");
        }
        return con;
    }
    /**
     * Creates new form Mesero
     */
    public Meseroejemplo() {
        initComponents();
     this.jButton1.setVisible(false);
     this.jButton2.setVisible(false);
     this.jButton3.setVisible(false);
     this.jButton4.setVisible(false);
     this.jButton5.setVisible(false);
     this.btnplatos1.setVisible(false);
     this.btnplatos2.setVisible(false);
     this.btnplatos3.setVisible(false);
     this.btnplatos4.setVisible(false);
     this.btnplatos5.setVisible(false);
     this.jTextField1.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnbebida = new javax.swing.JButton();
        btnpostres = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnplatos1 = new javax.swing.JButton();
        btnplatos2 = new javax.swing.JButton();
        btnplatos3 = new javax.swing.JButton();
        btnplatos4 = new javax.swing.JButton();
        btnplatos5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        btnenviar3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtprecio1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcantidad1 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnbebida.setBackground(new java.awt.Color(255, 204, 102));
        btnbebida.setText("BEBIDAS");
        btnbebida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnbebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        btnpostres.setBackground(new java.awt.Color(255, 204, 102));
        btnpostres.setText("PLATOS");
        btnpostres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnpostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostresActionPerformed(evt);
            }
        });
        getContentPane().add(btnpostres, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 170, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 204));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\IMAGENES\\BEBIDAS\\mirinda.png")); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, -1));

        jButton2.setBackground(new java.awt.Color(153, 255, 204));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\IMAGENES\\BEBIDAS\\sprite.png")); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 100, -1));

        jButton3.setBackground(new java.awt.Color(153, 255, 204));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\IMAGENES\\BEBIDAS\\seven.png")); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 100, -1));

        jButton4.setBackground(new java.awt.Color(153, 255, 204));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\IMAGENES\\BEBIDAS\\pepsi.png")); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, -1));

        jButton5.setBackground(new java.awt.Color(153, 255, 204));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\IMAGENES\\BEBIDAS\\cola.png")); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, -1));

        btnplatos1.setBackground(new java.awt.Color(153, 255, 204));
        btnplatos1.setIcon(new javax.swing.ImageIcon("C:\\IMAGENES\\PLATO FUERTE\\RES AL VINO TINTO.jpg")); // NOI18N
        btnplatos1.setText("           RES AL VINO TINTO");
        btnplatos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnplatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplatos1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnplatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 290, -1));

        btnplatos2.setBackground(new java.awt.Color(153, 255, 204));
        btnplatos2.setIcon(new javax.swing.ImageIcon("C:\\IMAGENES\\PLATO FUERTE\\POLLO A LA PARMESANA.jpeg.jpg")); // NOI18N
        btnplatos2.setText("POLLO A LA PARMESANA");
        btnplatos2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnplatos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplatos2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnplatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 290, -1));

        btnplatos3.setBackground(new java.awt.Color(153, 255, 204));
        btnplatos3.setIcon(new javax.swing.ImageIcon("C:\\IMAGENES\\PLATO FUERTE\\PENNE AL VODKA.jpg")); // NOI18N
        btnplatos3.setText("         PASTA AL VODKA            ");
        btnplatos3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnplatos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplatos3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnplatos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 290, -1));

        btnplatos4.setBackground(new java.awt.Color(153, 255, 204));
        btnplatos4.setIcon(new javax.swing.ImageIcon("C:\\IMAGENES\\PLATO FUERTE\\filete.png")); // NOI18N
        btnplatos4.setText("         FILETE DE PESACADO");
        btnplatos4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnplatos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplatos4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnplatos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 290, 80));

        btnplatos5.setBackground(new java.awt.Color(153, 255, 204));
        btnplatos5.setIcon(new javax.swing.ImageIcon("C:\\IMAGENES\\PLATO FUERTE\\ARROZ CON CAMARONES.jpg")); // NOI18N
        btnplatos5.setText("ARROZ CON CAMARONES");
        btnplatos5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnplatos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplatos5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnplatos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 290, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRECIO:");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, 20));

        txtprecio.setEnabled(false);
        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });
        getContentPane().add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 50, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 240, 30));

        btnnuevo.setText("NUEVO PEDIDO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 130, -1));

        btnenviar3.setText("AÑADIR");
        btnenviar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviar3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnenviar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 130, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLATO SELECCIONADO");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CANTIDAD");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, -1));

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 50, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 240, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRECIO:");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, 20));

        txtprecio1.setEnabled(false);
        txtprecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtprecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 50, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CANTIDAD");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, -1, -1));

        txtcantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtcantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 50, -1));

        jTextField1.setText("1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 30, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("INFORMACION DEPEDIDOS");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BEBIDA SELECCIONADA");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
jLabel5.setText("Pepsi");
txtprecio.setText("20");
txtcantidad.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jLabel5.setText("Sprite");
txtprecio.setText("20");
txtcantidad.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jLabel5.setText("Seven Up");
txtprecio.setText("20");
txtcantidad.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
jLabel5.setText("Coca Cola");
txtprecio.setText("20");
txtcantidad.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jLabel5.setText("Mirinda");
txtprecio.setText("20");
txtcantidad.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnplatos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplatos5ActionPerformed
jLabel2.setText("Arroz con Camarones");
txtprecio1.setText("170");
txtcantidad1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnplatos5ActionPerformed

    private void btnplatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplatos1ActionPerformed
jLabel2.setText("Res al Vino Tinto");
txtprecio1.setText("230");
txtcantidad1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnplatos1ActionPerformed

    private void btnplatos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplatos3ActionPerformed
jLabel2.setText("Pasta al Vodka");
txtprecio1.setText("220");
txtcantidad1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnplatos3ActionPerformed

    private void btnbebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebidaActionPerformed
 this.jButton1.setVisible(true);
     this.jButton2.setVisible(true);
     this.jButton3.setVisible(true);
     this.jButton4.setVisible(true);
     this.jButton5.setVisible(true); 
     this.btnplatos1.setVisible(false);
     this.btnplatos2.setVisible(false);
     this.btnplatos3.setVisible(false);
     this.btnplatos4.setVisible(false);
     this.btnplatos5.setVisible(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_btnbebidaActionPerformed

    private void btnpostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostresActionPerformed
this.btnplatos1.setVisible(true);
     this.btnplatos2.setVisible(true);
     this.btnplatos3.setVisible(true);
     this.btnplatos4.setVisible(true);
     this.btnplatos5.setVisible(true); 
          this.jButton1.setVisible(false);
     this.jButton2.setVisible(false);
     this.jButton3.setVisible(false);
     this.jButton4.setVisible(false);
     this.jButton5.setVisible(false);
     // TODO add your handling code here:
    }//GEN-LAST:event_btnpostresActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
int num,total;
num=Integer.parseInt(jTextField1.getText());
total=num+1;
jTextField1.setText(String.valueOf(total));
jLabel2.setText("");
        txtprecio1.setText("");
        txtcantidad1.setText("");
        jLabel5.setText("");
        txtprecio.setText("");
        txtcantidad.setText("");
     this.jButton1.setVisible(false);
     this.jButton2.setVisible(false);
     this.jButton3.setVisible(false);
     this.jButton4.setVisible(false);
     this.jButton5.setVisible(false);
     this.btnplatos1.setVisible(false);
     this.btnplatos2.setVisible(false);
     this.btnplatos3.setVisible(false);
     this.btnplatos4.setVisible(false);
     this.btnplatos5.setVisible(false);
     this.jTextField1.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnenviar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviar3ActionPerformed
dbManager modSql  = new dbManager();
        productObjectModel mod = new productObjectModel();
        Integer ord = Integer.parseInt(jTextField1.getText());
        String beb = jLabel5.getText();
        Float prib = Float.parseFloat(txtprecio.getText());
        Integer cantb = Integer.parseInt(txtcantidad.getText());
        String com = jLabel2.getText();
        Float pric = Float.parseFloat(txtprecio1.getText());
        Integer cantc = Integer.parseInt(txtcantidad1.getText());
        
        mod.setorderId(ord);
        mod.setBebida(beb);
        mod.setPriceb(prib);
        mod.setCantb(cantb);
        mod.setComida(com);
        mod.setPricec(pric);
        mod.setCantc(cantc);
        
      if(modSql.registerProducts(mod)){
        JOptionPane.showMessageDialog(null, "Registro guardado");
        } else{
            JOptionPane.showMessageDialog(null, "Error al guardar");
        }        //Agregar(); 
        jLabel2.setText("");
        txtprecio1.setText("");
        txtcantidad1.setText("");
        jLabel5.setText("");
        txtprecio.setText("");
        txtcantidad.setText("");
     this.jButton1.setVisible(false);
     this.jButton2.setVisible(false);
     this.jButton3.setVisible(false);
     this.jButton4.setVisible(false);
     this.jButton5.setVisible(false);
     this.btnplatos1.setVisible(false);
     this.btnplatos2.setVisible(false);
     this.btnplatos3.setVisible(false);
     this.btnplatos4.setVisible(false);
     this.btnplatos5.setVisible(false);
     this.jTextField1.setVisible(false);
        
    }//GEN-LAST:event_btnenviar3ActionPerformed

    private void btnplatos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplatos2ActionPerformed
jLabel2.setText("Pollo a la Parmesana");
txtprecio1.setText("180");
txtcantidad1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnplatos2ActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void btnplatos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplatos4ActionPerformed
jLabel2.setText("Filete de Pescado");
txtprecio1.setText("250");
txtcantidad1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnplatos4ActionPerformed

    private void txtprecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecio1ActionPerformed

    private void txtcantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidad1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meseroejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meseroejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meseroejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meseroejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meseroejemplo().setVisible(true);
            }
        });
    }
    
    void Agregar() {
        
        
        
    }
    
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbebida;
    private javax.swing.JButton btnenviar3;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnplatos1;
    private javax.swing.JButton btnplatos2;
    private javax.swing.JButton btnplatos3;
    private javax.swing.JButton btnplatos4;
    private javax.swing.JButton btnplatos5;
    private javax.swing.JButton btnpostres;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcantidad1;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprecio1;
    // End of variables declaration//GEN-END:variables
}
